# Site settings
title: Jhen's blog
email: iainst0409@gmail.com
description: > 
  I'm Jhen, this blog is my development notes. 
license: >
  Copyright © 2015 Jhen-Jie Hong. Powered by 
  <a href="http://jekyllrb.com" target="_blank">Jekyll.</a>
baseurl: ""
url: "http://jhen.me"
twitter_username: jhen_jie
facebook_username:  jhenjie.hong
github_username:  jhen0409


# Build settings
markdown: kramdown